### PR TITLE
Add Umbraco Forms querying and submitting

### PR DESCRIPTION
**Pull request by benjaminc**

### CODE REVIEW

**Comment by rasmusjp** [comment]
Hey, thanks for the PR. Sorry for not getting back to you sooner.

I've had a quick look and have a coupe of changes I'd like you to make

1. Move the new project to the `src` folder
2. Change it to a SDK project like the other projects

If you could add some tests too that would be ace (but not required) :)

**Comment by benjaminc** [comment]
I done both of the two changes you requested.  I don't have time to add unit tests this morning, but if I get a chance later today I'll add some.

**Comment by rasmusjp** [comment]
Cool and thanks, I can see the build is still failing though, looks like its because of `<PackageLicenseExpression>` in the `Our.Umbraco.GraphQL.Forms.csproj` file, I think it should be `PackageLicenseUrl` instead (which is on line 7).

I'll see if can get around to test it in the coming weekend (and create a release).

**Comment by benjaminc** [comment]
I started with PackageLicenseUrl, and my build failed locally telling me that the syntax wasn't valid anymore, and it needed to be switched to PackageLicenseExpression.  What version of VS are you using?

**Comment by rasmusjp** [comment]
Okay, it's the AppVeyor build https://ci.appveyor.com/project/rasmusjp/umbraco-graphql/builds/35091255 I can see it's running VS 2017 and dotnet cli 2.2.

But since both the build and test passes and only the package step fails, you don't need to do anything. I need to update the script and move to GitHub Actions anyways.

**Comment by rasmusjp** [comment]
Hi, I'm so sorry I haven't got around to look at you PR yet. I hope I can get around to look at it this weekend.

**Comment by mzajkowski** [comment]
To be moved to a separated repository / NuGet package ---> https://github.com/umbraco-community/umbraco-graphql-forms.

**Pull request merged**
